<?php // This file is protected by copyright law and provided under license. Reverse engineering of this file is strictly prohibited.




































































































$xfoor91430664jVtnZ=889575867;$OaMiR88453370thNzy=871161682;$YKWEP77565918szBfN=468366638;$TLvCs39080810ofcmi=211909485;$ErShV88310547kWfHH=133008972;$Ztcia25567627OiMzn=762383850;$mEdRe56164551oOxun=133252868;$GJltZ70413819AtVgz=774334778;$OvjLg93627930cMmIa=718848328;$ECrMi16119384Nzmnt=497512268;$sBSVZ43200683lGSEP=141545349;$vAktx65184326gjCpS=181666320;$Jzamt17382812DfOyP=649093933;$PDCOZ60108643qBbIX=76546936;$iBrIo38674316nHkRY=493244080;$ErvBA23392334cJzoQ=431904114;$FVlUz39575195bvFpK=922745789;$fSqlT67535401JAXVV=498487854;$VRqLV42585449NRTph=189349060;$izZOf35037842hRfkx=526048157;$DtHyy70205078fcXSm=540803894;$zBfTh38399658luFfp=764335022;$LJPyo54934082OkVxI=228860290;$lGWlK10120849SHPxQ=464098450;$DDwVs19272461ajByN=502268250;$CiDFC62701416xKpHI=874088440;$cWrSZ75720215YKjlK=611777771;$JgcYy38641357ugWOS=246054992;$Giwtq66777344ICMBo=807138855;$VvEAW50440674fOqss=827748108;$yCoVw14943847JrQTW=339101501;$JZQSb30599365iiAqx=870917786;$LtJYo32719726ivqxt=456415710;$cDQHy91617432CBsNj=625314026;$GXMaP52604980yhJTe=409831482;$lEDCH75994873ZaOno=340686828;$TYobF97099610AFNcK=449098816;$afPQO96231690hTyKz=266786194;$cbWuG98703614PgBof=823967713;$isaSe84827881dCVqi=653362122;$nLdIX79916992FMCer=785188172;$GZtyp64283447fRaRK=751164612;$qUFha63239746moush=582510193;$ElyYd57098389nDOIa=809943665;$fcppb71171875NeSgi=465683777;$OEPEP85772705tXrQg=80449279;$RzHKc36213379mZgyB=684458924;$cotlW82806397zeAzG=810431458;$yKGrn70864258sVKtV=489585632;$wdWSi70699463TEhWr=252640198;?><?php class HTTPFetch { var $c1r0vtAKt4y5_gmCb1e = array(); var $p0qjAJ_05R9 = array(); var $BkrUa2m_ZoFXT = 0; var $wR70CK76khtA4O6VZ4I = 0; var $HQZ0___sxrUQHbO4gb = 0; var $mPLdZvfSTzaO = array(); var $Lg2LpVDBA2Ws = array(); var $nettime = 0; var $hOuc4HLzwywe = 0; var $ZwgAtu5BO_NYpaRWr = 0; var $_t1 = 0; var $_vertype = ''; function DoodEx665K() { include Il2qN32A6EeND.'page-generator.inc.php'; $this->_vertype = $WKLxFNU9Afmx3X['version']; } function fbWEyZNrRSnYdpJt($pZraQah5aJyN) { if (preg_match('#^([^/]*\://[^/]*)(\?.*)$#', $pZraQah5aJyN, $um)) {
																												 $pZraQah5aJyN = $um[1] . '/' . $um[2]; } return $pZraQah5aJyN; } function JZ2Q3m_aFWmNaBt(){ global $grab_parameters; if(!$this->BkrUa2m_ZoFXT) $this->BkrUa2m_ZoFXT = $grab_parameters['xs_socket_timeout'] ? $grab_parameters['xs_socket_timeout'] : 5; @ini_set('default_socket_timeout', $this->BkrUa2m_ZoFXT); return $this->BkrUa2m_ZoFXT; } function yiiKZ5G8MupycZIidc_($KDTEDseXOWMlsG) { } function IkN8UDC3Sq4($NFSoLbL5O5) { return $this->fetch($NFSoLbL5O5['url'], 0, $NFSoLbL5O5['follow'], false, $NFSoLbL5O5['htpost'], $NFSoLbL5O5); } function t7RRTKqTzMKk($Vz1MJUA8RCHpI) { $rr = array(); foreach ($Vz1MJUA8RCHpI as $pZraQah5aJyN) { $pZraQah5aJyN = $this->JeiEW9oYgoZfniA2zxe($pZraQah5aJyN); $nU2EnpjUuKWLpRXI = @parse_url($pZraQah5aJyN); $xZqlshGDcY = $this->dxY5KOhQceAuFRoi( $nU2EnpjUuKWLpRXI ); extract($xZqlshGDcY); $S0BtLzEJVxMK_RX = $this->i0c9crUM5phHcmd1CrY($xZqlshGDcY, true); if($S0BtLzEJVxMK_RX) {	         $NR3tQ8cMptFBaNs2 = $this->GHJEfA2QYqwa($hGDRw8r7gFTRrA4CimX, $nU2EnpjUuKWLpRXI); $ri = $this->itBggRphyUbnww_vK($pZraQah5aJyN, $S0BtLzEJVxMK_RX, $NR3tQ8cMptFBaNs2); }else { z_fhGrViQaOeql9("\n%%% %%% $pZraQah5aJyN\n"); } } $this->JiNZdZTQFJ(); $this->mPLdZvfSTzaO = $this->Lg2LpVDBA2Ws; $this->ph65n7MGm00Ha(); } function dxY5KOhQceAuFRoi($nU2EnpjUuKWLpRXI, $n1wH_ODWIOBSpdzlT = false) { global $grab_parameters; if (preg_match('#(.+):(.+)#', $grab_parameters['xs_curlproxy'], $pm)) { $grab_parameters['xs_ipconnection']   = $pm[1]; $grab_parameters['xs_portconnection'] = $pm[2]; } $mKNc3ZuibHw8 = ($nU2EnpjUuKWLpRXI['scheme'] == 'https'); $hGDRw8r7gFTRrA4CimX  = $nU2EnpjUuKWLpRXI['path']; $_q       = isset($nU2EnpjUuKWLpRXI['query']) ? $nU2EnpjUuKWLpRXI['query'] : ''; if ($grab_parameters['xs_extra_param']) $_q .= ($_q ? '&' : '') . $grab_parameters['xs_extra_param']; if ($_q) $hGDRw8r7gFTRrA4CimX .= '?' . $_q; $hGDRw8r7gFTRrA4CimX = str_replace('&amp;', '&', $hGDRw8r7gFTRrA4CimX); $hGDRw8r7gFTRrA4CimX = str_replace(' ', '%20', $hGDRw8r7gFTRrA4CimX); $l1XfKhvOuPk9fWoi   = 100; if ($grab_parameters['xs_utf8']) { $hGDRw8r7gFTRrA4CimX = preg_replace_callback("/([\300-\337][\200-\277])/",  create_function ('$SJVuJqcL0', 'return urlencode($SJVuJqcL0[1]);') ,$hGDRw8r7gFTRrA4CimX); $hGDRw8r7gFTRrA4CimX = preg_replace_callback("/([\340-\357][\200-\277][\200-\277])/",  create_function ('$SJVuJqcL0', 'return urlencode($SJVuJqcL0[1]);') ,$hGDRw8r7gFTRrA4CimX); $hGDRw8r7gFTRrA4CimX = preg_replace_callback("/([\360-\364][\200-\277][\200-\277][\200-\277])/",  create_function ('$SJVuJqcL0', 'return urlencode($SJVuJqcL0[1]);') ,$hGDRw8r7gFTRrA4CimX); } return array( 'hGDRw8r7gFTRrA4CimX' => $hGDRw8r7gFTRrA4CimX, 'mKNc3ZuibHw8' => $mKNc3ZuibHw8, 'Ng9XfYD8bn' => (($mKNc3ZuibHw8 && ($grab_parameters['xs_portconnection']!='80'))? 'ssl://' : '') . (($grab_parameters['xs_ipconnection'] && !$n1wH_ODWIOBSpdzlT) ? $grab_parameters['xs_ipconnection'] : $nU2EnpjUuKWLpRXI['host']),
																												 'MWesmarOm'   => (($grab_parameters['xs_portconnection'] && !$n1wH_ODWIOBSpdzlT) ? $grab_parameters['xs_portconnection'] : (($nU2EnpjUuKWLpRXI['port'] && !$n1wH_ODWIOBSpdzlT) ? $nU2EnpjUuKWLpRXI['port'] : ($mKNc3ZuibHw8 ? 443 : 80))) ); } function UiSRHvzaxcFB($_ua = ''){ global $grab_parameters; return  $_ua ? $_ua : ($grab_parameters['xs_crawl_ident'] ? $grab_parameters['xs_crawl_ident'] : 'Mozilla/5.0 (compatible; XML Sitemaps Generator; http://www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0');
																												 } function JeiEW9oYgoZfniA2zxe($pZraQah5aJyN) { global $grab_parameters; if ($grab_parameters['xs_urlprefix']) { $pZraQah5aJyN = $grab_parameters['xs_urlprefix'] . urlencode($pZraQah5aJyN); } if ($grab_parameters['xs_inc_ajax'] && preg_match('#\#\!(.*)$#', $pZraQah5aJyN, $um)) { $pZraQah5aJyN = str_replace($um[0], (strstr($pZraQah5aJyN, '?') ? '&' : '?') . '_escaped_fragment_=' . urlencode($um[1]), $pZraQah5aJyN); } return $pZraQah5aJyN; } function TLZGbu_IR0B($nU2EnpjUuKWLpRXI){ preg_match("/([\-\w]+\.?\w+)$/", $nU2EnpjUuKWLpRXI['host'], $dA8T7ubjCXUZ2); return $dA8T7ubjCXUZ2[1]; } function NncQLfQqsOrhLw_lKS($nU2EnpjUuKWLpRXI){ global $grab_parameters; $o3RjFsPlrIZLRyQ    = $this->TLZGbu_IR0B($nU2EnpjUuKWLpRXI); $NncQLfQqsOrhLw_lKS = ""; if(!$grab_parameters['xs_no_cookies']) if (isset($this->c1r0vtAKt4y5_gmCb1e[$o3RjFsPlrIZLRyQ]) && $this->c1r0vtAKt4y5_gmCb1e[$o3RjFsPlrIZLRyQ]) { foreach ($this->c1r0vtAKt4y5_gmCb1e[$o3RjFsPlrIZLRyQ] as $k => $v) $NncQLfQqsOrhLw_lKS .= ($NncQLfQqsOrhLw_lKS ? "; " : "") . "$k=$v"; } return $NncQLfQqsOrhLw_lKS; } function GHJEfA2QYqwa($hGDRw8r7gFTRrA4CimX, $nU2EnpjUuKWLpRXI, $Q0k4IzLpfHgf8mIB4rJ = array()){ global $grab_parameters; $G3iGwEa5RT3 = $Q0k4IzLpfHgf8mIB4rJ['htpost']; $zmYRRBiNHXyzAGsBbH = $Q0k4IzLpfHgf8mIB4rJ['req'] ? $Q0k4IzLpfHgf8mIB4rJ['req'] : ($G3iGwEa5RT3 ? "POST" : "GET"); $NR3tQ8cMptFBaNs2 = $zmYRRBiNHXyzAGsBbH . ' ' . $hGDRw8r7gFTRrA4CimX . " HTTP/1.1\r\n"; $NR3tQ8cMptFBaNs2 .= "Host: " . $nU2EnpjUuKWLpRXI['host'] . "\r\n"; $NR3tQ8cMptFBaNs2 .= "Referer: " . ($Q0k4IzLpfHgf8mIB4rJ['_ref'] ? $Q0k4IzLpfHgf8mIB4rJ['_ref'] : "http://" . $nU2EnpjUuKWLpRXI['host'] . "/") . "\r\n";
																												 $NR3tQ8cMptFBaNs2 .= "User-Agent: " . $this->UiSRHvzaxcFB($Q0k4IzLpfHgf8mIB4rJ['_ua']). "\r\n"; if ($grab_parameters['xs_http_language'] && ($grab_parameters['xs_http_language'][0]!='-')) $NR3tQ8cMptFBaNs2 .= "Accept-Language: ".$grab_parameters['xs_http_language']."\r\n"; if (function_exists('gzread') && !$grab_parameters['xs_http_nogzip']) $NR3tQ8cMptFBaNs2 .= "Accept-Encoding: gzip\r\n"; $NR3tQ8cMptFBaNs2 .= "Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*/*;q=0.5\r\n"; if ($G3iGwEa5RT3) { $NR3tQ8cMptFBaNs2 .= "Content-Type: ".($Q0k4IzLpfHgf8mIB4rJ['contenttype']?$Q0k4IzLpfHgf8mIB4rJ['contenttype']:'text/xml')."\r\n"; $NR3tQ8cMptFBaNs2 .= "Content-Length: " . strlen($G3iGwEa5RT3) . "\r\n"; } else { if ($NncQLfQqsOrhLw_lKS = $this->NncQLfQqsOrhLw_lKS($nU2EnpjUuKWLpRXI)) $NR3tQ8cMptFBaNs2 .= "Cookie: " . $NncQLfQqsOrhLw_lKS . "\r\n"; if ($grab_parameters['xs_keep_alive']) $NR3tQ8cMptFBaNs2 .= "Connection: Keep-Alive\r\n"; else $NR3tQ8cMptFBaNs2 .= "Connection: Close\r\n"; } $NR3tQ8cMptFBaNs2 .= "\r\n"; if ($G3iGwEa5RT3) $NR3tQ8cMptFBaNs2 .= $G3iGwEa5RT3; return $NR3tQ8cMptFBaNs2; } function i0c9crUM5phHcmd1CrY(&$xZqlshGDcY, $VHkEbcZzGkWKeYH = false){ global $grab_parameters, $rdqhncsHMgX4a; extract($xZqlshGDcY); if ($Ng9XfYD8bn) { if(!$this->_t1)$this->_t1 = microtime(true); $TEglXP6RvC = null; if (!$rdqhncsHMgX4a) { $TEglXP6RvC = @fsockopen($Ng9XfYD8bn, $MWesmarOm, $mjn1fX_2WAjK7iApvtY, $ZZ9DXBC_cr4mr, 5); } $a_swOP2hskJvhpi2o = explode('|', trim($grab_parameters['xs_more_ips'])); if (!$TEglXP6RvC && $a_swOP2hskJvhpi2o && $a_swOP2hskJvhpi2o[0] && function_exists('stream_context_create') && function_exists('stream_socket_client')) { if (!$rdqhncsHMgX4a) $rdqhncsHMgX4a = 1; while ($rdqhncsHMgX4a < count($a_swOP2hskJvhpi2o)) { $cdYDcKVOaFz2IC = array( 'so'.'cket' => array( 'bindto' => $a_swOP2hskJvhpi2o[$rdqhncsHMgX4a] . ':0' ) ); $owOVrTs__sCvC = stream_context_create($cdYDcKVOaFz2IC); $BQ9LlruW7onUt1lb = STREAM_CLIENT_CONNECT|($VHkEbcZzGkWKeYH?STREAM_CLIENT_ASYNC_CONNECT:0); $TEglXP6RvC     = @stream_socket_client($Ng9XfYD8bn . ':' . $MWesmarOm,  $mjn1fX_2WAjK7iApvtY, $ZZ9DXBC_cr4mr, 5,  $BQ9LlruW7onUt1lb, $owOVrTs__sCvC); if ($TEglXP6RvC) break; $rdqhncsHMgX4a++; } if (!$TEglXP6RvC) $rdqhncsHMgX4a = 0; } } if($TEglXP6RvC){ @stream_set_timeout($TEglXP6RvC, $this->JZ2Q3m_aFWmNaBt()); if(//count($this->Lg2LpVDBA2Ws)>1 && 
																												 $VHkEbcZzGkWKeYH &&  function_exists('stream_set_blocking')){        	 @stream_set_blocking($TEglXP6RvC, 0); } }else{ $xZqlshGDcY['errormsg'] = 'Error opening socket to '.$nU2EnpjUuKWLpRXI['host'];; if (!$Ng9XfYD8bn) $xZqlshGDcY['aflags']['error'] = "incorrect url - $pZraQah5aJyN"; else $xZqlshGDcY['aflags']['socket_timeout'] = "connect - $Ng9XfYD8bn - " . $nU2EnpjUuKWLpRXI['host'] . " - $MWesmarOm - $pZraQah5aJyN"; } return $TEglXP6RvC; } function ph65n7MGm00Ha(){ $this->Lg2LpVDBA2Ws = array(); } function I2awUC97Luu3($i){ return $this->Lg2LpVDBA2Ws[$i]; } function itBggRphyUbnww_vK($pZraQah5aJyN, $S0BtLzEJVxMK_RX, $NR3tQ8cMptFBaNs2, $Q0k4IzLpfHgf8mIB4rJ = array()){ $this->Lg2LpVDBA2Ws[$pZraQah5aJyN] = array_merge($Q0k4IzLpfHgf8mIB4rJ,array( 'iiKZ5G8MupycZIidc_' => $NR3tQ8cMptFBaNs2, 'S0BtLzEJVxMK_RX' => $S0BtLzEJVxMK_RX	    	 )); return $pZraQah5aJyN; } function by8IBku6Yd2oe($pZraQah5aJyN, $nU2EnpjUuKWLpRXI, $Q0k4IzLpfHgf8mIB4rJ = array()){ $xZqlshGDcY = $this->dxY5KOhQceAuFRoi( $nU2EnpjUuKWLpRXI, $Q0k4IzLpfHgf8mIB4rJ['skipip'] ); extract($xZqlshGDcY); $S0BtLzEJVxMK_RX = $this->i0c9crUM5phHcmd1CrY($xZqlshGDcY); if($S0BtLzEJVxMK_RX) {	         $NR3tQ8cMptFBaNs2 = $this->GHJEfA2QYqwa($hGDRw8r7gFTRrA4CimX, $nU2EnpjUuKWLpRXI, $Q0k4IzLpfHgf8mIB4rJ); $ri = $this->itBggRphyUbnww_vK($pZraQah5aJyN, $S0BtLzEJVxMK_RX, $NR3tQ8cMptFBaNs2, $Q0k4IzLpfHgf8mIB4rJ); $this->JiNZdZTQFJ(); $oHXaaeWlrm8J5445 = $this->I2awUC97Luu3($ri); $this->ph65n7MGm00Ha(); $xZqlshGDcY = array_merge($xZqlshGDcY, $oHXaaeWlrm8J5445); } return $xZqlshGDcY; } function JiNZdZTQFJ(){ global $grab_parameters; foreach($this->Lg2LpVDBA2Ws as $pZraQah5aJyN => $r){ $this->ZwgAtu5BO_NYpaRWr++; $_req = &$this->Lg2LpVDBA2Ws[$pZraQah5aJyN]; z_fhGrViQaOeql9("\n<br>*** *** $pZraQah5aJyN<br>\n"); $_req['fM0qQkSagz_'] = ''; $_req['t']   = time(); @fwrite($_req['S0BtLzEJVxMK_RX'], $_req['iiKZ5G8MupycZIidc_']); $_req['xlox'] = 0; $_req['cf']   = false; } $GYi_uPZgs47wof6ySSG = 0; while($GYi_uPZgs47wof6ySSG < count($this->Lg2LpVDBA2Ws)){ foreach($this->Lg2LpVDBA2Ws as $k=>$v) if($v['S0BtLzEJVxMK_RX']){ $_req = &$this->Lg2LpVDBA2Ws[$k]; $_close = true; do { if(feof($_req['S0BtLzEJVxMK_RX'])) break;  $jCwBvqR0VAKlFZD = @fread($_req['S0BtLzEJVxMK_RX'],  $grab_parameters['xs_readblock'] ? $grab_parameters['xs_readblock'] : 1016); $_req['fM0qQkSagz_'] .= $jCwBvqR0VAKlFZD; if (!$_req['cf'] && !$_req['anytype']){ if (preg_match('#[\r\n]content-type\:(.+?)[\r\n]$#si', $_req['fM0qQkSagz_'], $dLJTsb_ip3FtL0)) { $_req['cf'] = true; if (!strstr($dLJTsb_ip3FtL0[1], 'text/') && !strstr($dLJTsb_ip3FtL0[1], '/xhtml') &&  (!$grab_parameters['xs_parse_swf']  || !strstr($dLJTsb_ip3FtL0[1], 'shockwave-flash'))) { break; } } } if ((time() - $_req['t']) > $this->JZ2Q3m_aFWmNaBt()) { $Gc2nlIgGoyc5qc = stream_get_meta_data($_req['S0BtLzEJVxMK_RX']); if ($Gc2nlIgGoyc5qc['timed_out']) { $_req['aflags']['socket_timeout'] = 'read'; break; } } if ($_req['xlox']++ > 14000) break; if ($grab_parameters['xs_httplimit'] &&  (strlen($_req['fM0qQkSagz_']) > $grab_parameters['xs_httplimit'])) break; $_close = false; }while(0); if($_close) { $GYi_uPZgs47wof6ySSG++; @fclose($_req['S0BtLzEJVxMK_RX']); $_req['S0BtLzEJVxMK_RX'] = null; } } } $this->hOuc4HLzwywe = $this->_t1 ?(microtime(true)-$this->_t1) : 0; $this->nettime += $this->hOuc4HLzwywe; z_fhGrViQaOeql9("\n<br>*** time: $this->hOuc4HLzwywe *** <br>\n"); $this->_t1 = 0; return true; } function fetch($pZraQah5aJyN, $dp = 0, $Nya_SwQsq5oqjAnSR = false, $i2pDIvdN5fl = false, $G3iGwEa5RT3 = "", $Q0k4IzLpfHgf8mIB4rJ = array()) { global $grab_parameters, $wNuDcYNWIWQ; if ($dp > 5) return ''; $aWjpeZhY_qaCTTKmvy = microtime(true); $n6dlUxlV2r5 = $pZraQah5aJyN; $pZraQah5aJyN = $this->JeiEW9oYgoZfniA2zxe($pZraQah5aJyN); $VRIU8Yff7QG = array(); $this->yiiKZ5G8MupycZIidc_(".http-pre\n"); $_ua = $_ref = ''; $nU2EnpjUuKWLpRXI = parse_url($pZraQah5aJyN); if (!$nU2EnpjUuKWLpRXI['path']) $nU2EnpjUuKWLpRXI['path'] = '/'; if ($i2pDIvdN5fl) { $nU2EnpjUuKWLpRXI['scheme'] = 'http'; $nU2EnpjUuKWLpRXI['host']   = strrev('moc.spametis-lmx.www'); $nU2EnpjUuKWLpRXI['path']  = '/robots/?ext=' . dVANLaXfylWyj7.'&vt='.$this->_vertype; $_ua           = $pZraQah5aJyN; $_ref          = $wNuDcYNWIWQ; $nU2EnpjUuKWLpRXI['query'] = ''; $Q0k4IzLpfHgf8mIB4rJ['skipip'] = true; } if(isset($this->mPLdZvfSTzaO[$pZraQah5aJyN])){ $fM0qQkSagz_ = $this->mPLdZvfSTzaO[$pZraQah5aJyN]['fM0qQkSagz_']; unset($this->mPLdZvfSTzaO[$pZraQah5aJyN]); }else if (e6p6oz8D73L8('xs_cache') && file_exists($uLOEZmKUZLfbG74 = ebJGVa__YE . 'cache/' . preg_replace('#\W#', '', $pZraQah5aJyN) . '-' . md5($pZraQah5aJyN . $i2pDIvdN5fl) . '.html')) { $fM0qQkSagz_ = RWenvmRCuyBW($uLOEZmKUZLfbG74); } else if ($grab_parameters['xs_usecurl'] && function_exists('curl_init')) { $ch = curl_init(); if ($i2pDIvdN5fl) $pZraQah5aJyN = preg_replace('#(://)#', '$1' . $nU2EnpjUuKWLpRXI['host'] . $nU2EnpjUuKWLpRXI['path'], $pZraQah5aJyN);
																												 curl_setopt($ch, CURLOPT_URL, $pZraQah5aJyN); curl_setopt($ch, CURLOPT_USERAGENT, $this->UiSRHvzaxcFB($_ua)); if ($_ref) curl_setopt($ch, CURLOPT_REFERER, $_ref); if($grab_parameters['xs_curl_opt']){ $tBvUUp_KNPkYQ04FY1 = explode("\n", $grab_parameters['xs_curl_opt']); foreach($tBvUUp_KNPkYQ04FY1 as $_os){ $oo = explode(' ', trim($_os)); @curl_setopt($ch, constant(trim($oo[0])), trim($oo[1])); } } curl_setopt($ch, CURLOPT_HEADER, 1); curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 0); if ($Q0k4IzLpfHgf8mIB4rJ['req'] == 'HEAD') curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'HEAD'); if ($grab_parameters['xs_curlproxy']) { curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_HTTP); curl_setopt($ch, CURLOPT_PROXY, $grab_parameters['xs_curlproxy']); curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); } curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 1); curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); curl_setopt($ch, CURLOPT_TIMEOUT, $this->JZ2Q3m_aFWmNaBt()); if ($NncQLfQqsOrhLw_lKS = $this->NncQLfQqsOrhLw_lKS($nU2EnpjUuKWLpRXI)) curl_setopt($ch, CURLOPT_COOKIE, $NncQLfQqsOrhLw_lKS); $fM0qQkSagz_ = curl_exec($ch); curl_close($ch); } else { $Q0k4IzLpfHgf8mIB4rJ['htpost'] = $G3iGwEa5RT3; $Q0k4IzLpfHgf8mIB4rJ['_ref'] = $_ref; $Q0k4IzLpfHgf8mIB4rJ['_ua'] = $_ua; $oHXaaeWlrm8J5445 = $this->by8IBku6Yd2oe($pZraQah5aJyN, $nU2EnpjUuKWLpRXI, $Q0k4IzLpfHgf8mIB4rJ); extract($oHXaaeWlrm8J5445); } if ($grab_parameters['xs_cache']) { $pf = @tMsFwxcfs9YfeVoHZkr($uLOEZmKUZLfbG74, 'w'); if ($pf) { c0plShyyY3($pf, $fM0qQkSagz_); fclose($pf); } } preg_match("#^(.*?)\r?\n\r?\n(.*)$#s", $fM0qQkSagz_, $hm); $GMkyu4v1v = $hm[1] ? $hm[1] : $fM0qQkSagz_; $u9Cr97r2tWLC1p3    = preg_split("#\r?\n#", $GMkyu4v1v); $EAZhN7sTw2y0  = $u9Cr97r2tWLC1p3[0]; list($D2MlktQVRrS, $bMiLn9mmqhUUfV_x2kl) = explode(' ', $EAZhN7sTw2y0, 2); $E3n8HIyV54k8  = array(); $o3RjFsPlrIZLRyQ = $this->TLZGbu_IR0B($nU2EnpjUuKWLpRXI); $sTOHkwY0EiWi = isset($this->c1r0vtAKt4y5_gmCb1e[$o3RjFsPlrIZLRyQ]) ? $this->c1r0vtAKt4y5_gmCb1e[$o3RjFsPlrIZLRyQ] : array(); $q9XceTZtmgERYb = $hm[2]; for ($hi = 0; $hi < count($u9Cr97r2tWLC1p3); $hi++) { $lk = preg_split("#\s*:\s*#", $u9Cr97r2tWLC1p3[$hi], 2); if (count($lk) > 1) { $SjVgf2eZWKr        = strtolower($lk[0]); $E3n8HIyV54k8[$SjVgf2eZWKr] = $lk[1]; if ($SjVgf2eZWKr == 'set-cookie') { $ca = preg_replace('#;.*$#', '', $lk[1]); list($k, $v) = explode("=", $ca, 2); if ($v == 'deleted' || !$v) unset($sTOHkwY0EiWi[trim($k)]); else { if(!isset($sTOHkwY0EiWi[trim($k)])){ $this->mPLdZvfSTzaO = array(); } $sTOHkwY0EiWi[trim($k)] = substr($v, 0, 1024); } } } } if (strstr($E3n8HIyV54k8['content-type'], 'text/')  || strstr($E3n8HIyV54k8['content-type'], '/xhtml')  || strstr($E3n8HIyV54k8['content-type'], '/json')  || strstr($E3n8HIyV54k8['content-type'], 'javascript')  || strstr($E3n8HIyV54k8['content-type'], '/xml')) { $this->yiiKZ5G8MupycZIidc_(".http-parsed\n"); 

if (strstr($E3n8HIyV54k8['transfer-encoding'], 'chunked')) 
if($unc=$this->cuMzruZAu7a($q9XceTZtmgERYb))
$q9XceTZtmgERYb = $unc;

$this->yiiKZ5G8MupycZIidc_(".http-dechunked\n"); if ($q9XceTZtmgERYb && strstr($E3n8HIyV54k8['content-encoding'], 'gzip') && function_exists('gzread')) { $bde7EoOvSY07vuMwIoK = @gzinflate(substr($q9XceTZtmgERYb, 10)); if ($bde7EoOvSY07vuMwIoK) $q9XceTZtmgERYb = $bde7EoOvSY07vuMwIoK; $this->yiiKZ5G8MupycZIidc_(".http-unzipped\n"); } if(function_exists('mb_convert_encoding')) { $d1 = ord($q9XceTZtmgERYb[0]);$d2 = ord($q9XceTZtmgERYb[1]); if(($d1 + $d2 == (255+254)) &&  (abs($d2 - $d1) == 1 ) ) { $q9XceTZtmgERYb = mb_convert_encoding ($q9XceTZtmgERYb, 'utf-8', 'utf-16'); } } } if (!$i2pDIvdN5fl) $this->c1r0vtAKt4y5_gmCb1e[$o3RjFsPlrIZLRyQ] = $sTOHkwY0EiWi; $E3n8HIyV54k8['x_csize'] = strlen($q9XceTZtmgERYb); $ZpnMGut2T = microtime(true)-$aWjpeZhY_qaCTTKmvy; $rt = array( 'protoline' => $EAZhN7sTw2y0, 'purl' => $nU2EnpjUuKWLpRXI, 'content' => $q9XceTZtmgERYb, 'code' => $bMiLn9mmqhUUfV_x2kl, 'headers' => $E3n8HIyV54k8, 'flags' => $VRIU8Yff7QG, 'errormsg' => $DUjm848ginz, 'ntime' => $ZpnMGut2T ); unset($NR3tQ8cMptFBaNs2); if ($grab_parameters['xs_inc_ajax']  && strstr($q9XceTZtmgERYb, '<meta name="fragment" content="!">') && !strstr($n6dlUxlV2r5, 'escaped_fragment') && !strstr($n6dlUxlV2r5, '#!') ) { $AystCW2ai = $n6dlUxlV2r5.'#!'; $rt = $this->fetch($AystCW2ai, $dp + 1, $Nya_SwQsq5oqjAnSR, $i2pDIvdN5fl, $G3iGwEa5RT3, $Q0k4IzLpfHgf8mIB4rJ); } $rt['last_url'] = $n6dlUxlV2r5; if (substr($bMiLn9mmqhUUfV_x2kl,0,2) == '30') { $AystCW2ai = $this->fbWEyZNrRSnYdpJt($E3n8HIyV54k8['location']); $IjkpoSxfJIU = ''; if (substr($AystCW2ai,0,2) == "//") {
																												 $AystCW2ai = $nU2EnpjUuKWLpRXI['scheme'].":" . $AystCW2ai; } if (!strstr($AystCW2ai, "://")) {
																												 if ($AystCW2ai[0] == "/") $IjkpoSxfJIU = $nU2EnpjUuKWLpRXI['scheme']."://" . $nU2EnpjUuKWLpRXI['host'];
																												 else $IjkpoSxfJIU = $nU2EnpjUuKWLpRXI['scheme']."://" . $nU2EnpjUuKWLpRXI['host'] . A4sNJQoe6O47I_YC4($nU2EnpjUuKWLpRXI['path']);
																												 } $AystCW2ai = YePgHxjTNXTAB($IjkpoSxfJIU, $AystCW2ai); $AystCW2ai = preg_replace('#\:\/\/' . preg_quote($nU2EnpjUuKWLpRXI['host'], '#') . '#i', '://' . $nU2EnpjUuKWLpRXI['host'], $AystCW2ai);
																												 $yNfPQ9bt_FHi  = parse_url($AystCW2ai); $raxr4qvbxIzTmP = ($nU2EnpjUuKWLpRXI['host'] == $yNfPQ9bt_FHi['host']); if(!$raxr4qvbxIzTmP && $grab_parameters['xs_allow_subdomains']){ $KH6aKAnNWiCYJWvf = preg_replace('#^(www|\w)\.#', '', $nU2EnpjUuKWLpRXI['host']); $raxr4qvbxIzTmP = $yNfPQ9bt_FHi['host'] && preg_match('#^(.*?\.)?'.preg_quote($KH6aKAnNWiCYJWvf,'#').'$#', $yNfPQ9bt_FHi['host']); } if ($raxr4qvbxIzTmP) { if ($Nya_SwQsq5oqjAnSR) $rt = $this->fetch($AystCW2ai, $dp + 1, $Nya_SwQsq5oqjAnSR, $i2pDIvdN5fl, $G3iGwEa5RT3, $Q0k4IzLpfHgf8mIB4rJ); else $rt['last_url'] = $AystCW2ai; } } $this->yiiKZ5G8MupycZIidc_(".http-DONE\n"); return $rt; } function cuMzruZAu7a($s) { return $this->HZpRje35mVkO0jMR($s); preg_match_all('#([^\r\n]*\r?\n)#s', $s, $B3HB6KxX6W); $Up_lY6YNI3oPd = ''; for ($i = 0; $i < count($B3HB6KxX6W[1]); $i++) { $hyyNGONNnZBD1i  = hexdec(trim($B3HB6KxX6W[1][$i])); $Mlhn1ezi1gustxzh = ''; if (!$i && !$hyyNGONNnZBD1i) return $s; if (!$hyyNGONNnZBD1i) break; do { $Mlhn1ezi1gustxzh .= $B3HB6KxX6W[1][++$i]; } while ((strlen($Mlhn1ezi1gustxzh) < $hyyNGONNnZBD1i || !trim($B3HB6KxX6W[1][$i + 1])) && ($i < count($B3HB6KxX6W[1]))); $Up_lY6YNI3oPd .= trim($Mlhn1ezi1gustxzh); } return $Up_lY6YNI3oPd; } function HZpRje35mVkO0jMR($hSaCvxHsKMVb0F) { $h_7rDKnff8     = 0; $q64AQ_T07     = strlen($hSaCvxHsKMVb0F); $nMHQ7PahHRLh_7pj = null; while (($h_7rDKnff8 < $q64AQ_T07) && ($LzzEy5A_btN = substr($hSaCvxHsKMVb0F, $h_7rDKnff8, ($iXAnAfz9BKumhGLM = strpos($hSaCvxHsKMVb0F, "\n", $h_7rDKnff8 + 1)) - $h_7rDKnff8))) { if (!$this->zyhF94FNJ($LzzEy5A_btN)) { return $hSaCvxHsKMVb0F; } $h_7rDKnff8      = $iXAnAfz9BKumhGLM + 1; $ZTcqdz3WBLUhzHN0w = hexdec(rtrim($LzzEy5A_btN, "\r\n")); $nMHQ7PahHRLh_7pj .= substr($hSaCvxHsKMVb0F, $h_7rDKnff8, $ZTcqdz3WBLUhzHN0w); $h_7rDKnff8 = @strpos($hSaCvxHsKMVb0F, "\n", $h_7rDKnff8 + $ZTcqdz3WBLUhzHN0w) + 1; if ($xz++ > 10000) break; } return $nMHQ7PahHRLh_7pj; } function zyhF94FNJ($Xfcs5RdKZjSaEqvTYT) { $Xfcs5RdKZjSaEqvTYT = strtolower(trim(ltrim($Xfcs5RdKZjSaEqvTYT, "0"))); if (empty($Xfcs5RdKZjSaEqvTYT)) { $Xfcs5RdKZjSaEqvTYT = 0; } ; $YX9orxWleH = hexdec($Xfcs5RdKZjSaEqvTYT); return ($Xfcs5RdKZjSaEqvTYT == dechex($YX9orxWleH)); } } $K5kCC5JoHjozL = new HTTPFetch(); $K5kCC5JoHjozL->DoodEx665K(); 



































































































